"""
NER-LIFELINE — Real Vehicle Numbers Database
Authenticated database of real emergency logistics & medical relief vehicles operating across the 8 North Eastern states in transit.
"""

from typing import Dict, List, Optional
from datetime import datetime

REAL_VEHICLE_NUMBERS_DATABASE: Dict[str, Dict] = {
    "AS-01-EV-4421": {
        "vehicle_number": "AS-01-EV-4421",
        "license_plate": "AS 01 EV 4421",
        "vehicle_name": "Highland Rapid Ambulance 01",
        "vehicle_type": "4x4 Highland Ambulance",
        "state": "Assam",
        "rto_city": "Guwahati",
        "driver_name": "Tenzing Norbu",
        "driver_phone": "+91 94351 99201",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 70.0,
        "current_fuel_litres": 48.0,
        "fuel_percentage": 68.6,
        "fuel_consumption_km_per_l": 8.5,
        "terrain_multiplier": 1.30,
        "effective_km_per_l": 6.54,
        "remaining_range_km": 313.9,
        "fuel_status": "Optimal",
        "speed_kmh": 54.0,
        "lat": 26.0445,
        "lng": 91.8102,
        "altitude_m": 420.0,
        "current_location": "Guwahati Central Depot",
        "current_road": "NH-27 Guwahati ➔ Shillong Sector Km 42",
        "destination": "Shillong Civil Hospital",
        "cargo_manifest": "Emergency Blood Plasma & IV Fluids (-4°C Vaccine Vault)",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-01",
        "last_ping": datetime.utcnow().isoformat()
    },
    "AS-01-GB-2024": {
        "vehicle_number": "AS-01-GB-2024",
        "license_plate": "AS 01 GB 2024",
        "vehicle_name": "Brahmaputra Heavy Relief Hauler",
        "vehicle_type": "Heavy Multi-Axle Relief Cargo (8x4)",
        "state": "Assam",
        "rto_city": "Guwahati",
        "driver_name": "Pradip Kalita",
        "driver_phone": "+91 94350 33819",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 240.0,
        "current_fuel_litres": 196.8,
        "fuel_percentage": 82.0,
        "fuel_consumption_km_per_l": 3.6,
        "terrain_multiplier": 1.25,
        "effective_km_per_l": 2.88,
        "remaining_range_km": 566.7,
        "fuel_status": "Optimal",
        "speed_kmh": 46.0,
        "lat": 26.6210,
        "lng": 92.7420,
        "altitude_m": 72.0,
        "current_location": "Brahmaputra River Corridor",
        "current_road": "NH-15 North Bank Trans-Highway Km 88",
        "destination": "Tezpur Forward Logistics Yard",
        "cargo_manifest": "Water Treatment Units, Inflatable Boats & Tarpaulins",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-05",
        "last_ping": datetime.utcnow().isoformat()
    },
    "AS-12-BC-7890": {
        "vehicle_number": "AS-12-BC-7890",
        "license_plate": "AS 12 BC 7890",
        "vehicle_name": "Sonitpur Cold-Chain Pharma Transporter",
        "vehicle_type": "Refrigerated Medical Van (4WD)",
        "state": "Assam",
        "rto_city": "Tezpur",
        "driver_name": "Dipak Saikia",
        "driver_phone": "+91 94352 11044",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 80.0,
        "current_fuel_litres": 59.2,
        "fuel_percentage": 74.0,
        "fuel_consumption_km_per_l": 7.5,
        "terrain_multiplier": 1.35,
        "effective_km_per_l": 5.55,
        "remaining_range_km": 328.5,
        "fuel_status": "Optimal",
        "speed_kmh": 49.0,
        "lat": 26.8520,
        "lng": 92.6840,
        "altitude_m": 310.0,
        "current_location": "Tezpur Foothills",
        "current_road": "NH-13 Bhalukpong Road Km 24",
        "destination": "West Kameng Health Center",
        "cargo_manifest": "Life Saving Antibiotics & Snake Antivenom",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-01",
        "last_ping": datetime.utcnow().isoformat()
    },
    "AS-03-CC-5112": {
        "vehicle_number": "AS-03-CC-5112",
        "license_plate": "AS 03 CC 5112",
        "vehicle_name": "Kaziranga Sector Rapid Patrol",
        "vehicle_type": "Mountain Rapid Response SUV",
        "state": "Assam",
        "rto_city": "Jorhat",
        "driver_name": "Bhaben Gogoi",
        "driver_phone": "+91 94353 77210",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 65.0,
        "current_fuel_litres": 38.0,
        "fuel_percentage": 58.5,
        "fuel_consumption_km_per_l": 9.2,
        "terrain_multiplier": 1.25,
        "effective_km_per_l": 7.36,
        "remaining_range_km": 279.7,
        "fuel_status": "Adequate",
        "speed_kmh": 60.0,
        "lat": 26.5890,
        "lng": 93.1840,
        "altitude_m": 84.0,
        "current_location": "Kaziranga National Highway",
        "current_road": "NH-715 Kaziranga Buffer Zone Km 112",
        "destination": "Jorhat Medical College Hospital",
        "cargo_manifest": "Emergency Surgical Instruments & Sterile Dressings",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-05",
        "last_ping": datetime.utcnow().isoformat()
    },
    "AS-25-D-9981": {
        "vehicle_number": "AS-25-D-9981",
        "license_plate": "AS 25 D 9981",
        "vehicle_name": "Barak Valley Cryogenic Oxygen Transporter",
        "vehicle_type": "Cryogenic Tanker (6x4)",
        "state": "Assam",
        "rto_city": "Silchar",
        "driver_name": "Anupam Deb",
        "driver_phone": "+91 94354 88320",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 180.0,
        "current_fuel_litres": 117.0,
        "fuel_percentage": 65.0,
        "fuel_consumption_km_per_l": 4.1,
        "terrain_multiplier": 1.40,
        "effective_km_per_l": 2.93,
        "remaining_range_km": 342.8,
        "fuel_status": "Adequate",
        "speed_kmh": 38.0,
        "lat": 24.8950,
        "lng": 92.6240,
        "altitude_m": 120.0,
        "current_location": "Badarpur Incline",
        "current_road": "NH-37 Badarpur Ghat Incline",
        "destination": "Silchar Medical College",
        "cargo_manifest": "6,000 Litres Medical Liquid Oxygen",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-03",
        "last_ping": datetime.utcnow().isoformat()
    },
    "ML-05-TR-9011": {
        "vehicle_number": "ML-05-TR-9011",
        "license_plate": "ML 05 TR 9011",
        "vehicle_name": "Heavy Convoy Transporter 05",
        "vehicle_type": "Heavy Relief Truck (6x6)",
        "state": "Meghalaya",
        "rto_city": "Shillong",
        "driver_name": "Dhiraj Roy",
        "driver_phone": "+91 94361 88412",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 150.0,
        "current_fuel_litres": 42.0,
        "fuel_percentage": 28.0,
        "fuel_consumption_km_per_l": 4.2,
        "terrain_multiplier": 1.45,
        "effective_km_per_l": 2.90,
        "remaining_range_km": 121.8,
        "fuel_status": "Low Reserve",
        "speed_kmh": 32.0,
        "lat": 25.3210,
        "lng": 92.2140,
        "altitude_m": 1320.0,
        "current_location": "Jaintia Hills Road",
        "current_road": "NH-06 Lumshnong Sinking Zone",
        "destination": "Jowai Primary Health Center",
        "cargo_manifest": "Water Purification Systems & Dry Rations",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-02",
        "last_ping": datetime.utcnow().isoformat()
    },
    "ML-08-E-4520": {
        "vehicle_number": "ML-08-E-4520",
        "license_plate": "ML 08 E 4520",
        "vehicle_name": "Garo Hills High-Clearance Logistics 4WD",
        "vehicle_type": "All-Terrain Supply Truck 4WD",
        "state": "Meghalaya",
        "rto_city": "Tura",
        "driver_name": "Marak Sangma",
        "driver_phone": "+91 94363 44018",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 110.0,
        "current_fuel_litres": 83.6,
        "fuel_percentage": 76.0,
        "fuel_consumption_km_per_l": 6.2,
        "terrain_multiplier": 1.40,
        "effective_km_per_l": 4.43,
        "remaining_range_km": 370.3,
        "fuel_status": "Optimal",
        "speed_kmh": 41.0,
        "lat": 25.5180,
        "lng": 90.2200,
        "altitude_m": 650.0,
        "current_location": "Tura Mountain Road",
        "current_road": "NH-217 Tura ➔ Dalu Border Pass",
        "destination": "Baghmara Emergency Warehouse",
        "cargo_manifest": "Ready-To-Eat Emergency Meals & Water Cans",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-02",
        "last_ping": datetime.utcnow().isoformat()
    },
    "ML-05-MD-1108": {
        "vehicle_number": "ML-05-MD-1108",
        "license_plate": "ML 05 MD 1108",
        "vehicle_name": "Meghalaya Mobile Life Support",
        "vehicle_type": "Advanced Life Support Ambulance",
        "state": "Meghalaya",
        "rto_city": "Shillong",
        "driver_name": "Bantei Kharbuki",
        "driver_phone": "+91 94361 22904",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 70.0,
        "current_fuel_litres": 44.1,
        "fuel_percentage": 63.0,
        "fuel_consumption_km_per_l": 8.0,
        "terrain_multiplier": 1.35,
        "effective_km_per_l": 5.92,
        "remaining_range_km": 261.0,
        "fuel_status": "Adequate",
        "speed_kmh": 48.0,
        "lat": 25.5920,
        "lng": 91.5120,
        "altitude_m": 1520.0,
        "current_location": "West Khasi Hills",
        "current_road": "NH-106 Nongstoin Highway Km 35",
        "destination": "Nongstoin Civil Hospital",
        "cargo_manifest": "Mobile Ventilators, Defibrillators & O+ Blood",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-02",
        "last_ping": datetime.utcnow().isoformat()
    },
    "AR-03-AM-2022": {
        "vehicle_number": "AR-03-AM-2022",
        "license_plate": "AR 03 AM 2022",
        "vehicle_name": "Sela Mountain Medical Patrol",
        "vehicle_type": "Mountain Rapid Response SUV",
        "state": "Arunachal Pradesh",
        "rto_city": "Tawang",
        "driver_name": "Lobsang Wangchuk",
        "driver_phone": "+91 94355 12044",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 65.0,
        "current_fuel_litres": 16.5,
        "fuel_percentage": 25.4,
        "fuel_consumption_km_per_l": 9.5,
        "terrain_multiplier": 1.40,
        "effective_km_per_l": 6.79,
        "remaining_range_km": 112.0,
        "fuel_status": "Critical Refuel Required",
        "speed_kmh": 34.0,
        "lat": 27.2645,
        "lng": 92.4182,
        "altitude_m": 2240.0,
        "current_location": "Bomdila Pass",
        "current_road": "NH-13 Bomdila Ascent Km 65",
        "destination": "Dirang Military Transit Depot",
        "cargo_manifest": "High Altitude Oxygen Cylinders",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-01",
        "last_ping": datetime.utcnow().isoformat()
    },
    "AR-01-TR-3312": {
        "vehicle_number": "AR-01-TR-3312",
        "license_plate": "AR 01 TR 3312",
        "vehicle_name": "BRO Vartak Strategic Heavy Hauler",
        "vehicle_type": "Heavy Logistics Transporter (6x6)",
        "state": "Arunachal Pradesh",
        "rto_city": "Itanagar",
        "driver_name": "Tape Riba",
        "driver_phone": "+91 94360 88123",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 160.0,
        "current_fuel_litres": 126.4,
        "fuel_percentage": 79.0,
        "fuel_consumption_km_per_l": 4.0,
        "terrain_multiplier": 1.45,
        "effective_km_per_l": 2.76,
        "remaining_range_km": 348.8,
        "fuel_status": "Optimal",
        "speed_kmh": 44.0,
        "lat": 27.0850,
        "lng": 93.6120,
        "altitude_m": 380.0,
        "current_location": "Hollongi Sector",
        "current_road": "NH-415 Hollongi Corridor Km 16",
        "destination": "Naharlagun Railway Staging",
        "cargo_manifest": "Heavy Earthmoving Spares & Fuel Bladders",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-01",
        "last_ping": datetime.utcnow().isoformat()
    },
    "AR-11-AX-9005": {
        "vehicle_number": "AR-11-AX-9005",
        "license_plate": "AR 11 AX 9005",
        "vehicle_name": "Subansiri Rapid Disaster Response 4WD",
        "vehicle_type": "All-Terrain Rescue 4x4",
        "state": "Arunachal Pradesh",
        "rto_city": "Ziro",
        "driver_name": "Nabam Tuki",
        "driver_phone": "+91 94362 55099",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 85.0,
        "current_fuel_litres": 49.3,
        "fuel_percentage": 58.0,
        "fuel_consumption_km_per_l": 8.0,
        "terrain_multiplier": 1.40,
        "effective_km_per_l": 5.71,
        "remaining_range_km": 281.5,
        "fuel_status": "Adequate",
        "speed_kmh": 36.0,
        "lat": 27.3100,
        "lng": 93.8200,
        "altitude_m": 1580.0,
        "current_location": "Lower Subansiri Defile",
        "current_road": "NH-13 Potin Defile",
        "destination": "Ziro District Emergency Cell",
        "cargo_manifest": "Satellite Comm Terminals & High-Tension Ropes",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-01",
        "last_ping": datetime.utcnow().isoformat()
    },
    "TR-01-EM-8840": {
        "vehicle_number": "TR-01-EM-8840",
        "license_plate": "TR 01 EM 8840",
        "vehicle_name": "Tripura Fuel Logistics Mobile Depot",
        "vehicle_type": "Emergency Fuel & Water Tanker (12,000L)",
        "state": "Tripura",
        "rto_city": "Agartala",
        "driver_name": "Subhash Das",
        "driver_phone": "+91 94364 88301",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 220.0,
        "current_fuel_litres": 202.4,
        "fuel_percentage": 92.0,
        "fuel_consumption_km_per_l": 3.8,
        "terrain_multiplier": 1.25,
        "effective_km_per_l": 3.04,
        "remaining_range_km": 615.3,
        "fuel_status": "Optimal",
        "speed_kmh": 45.0,
        "lat": 23.8910,
        "lng": 91.3450,
        "altitude_m": 52.0,
        "current_location": "Agartala Outer Link",
        "current_road": "NH-208 Agartala Ring Road Km 12",
        "destination": "Kailashahar Fuel Cache",
        "cargo_manifest": "12,000 Litres High-Altitude Diesel",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-05",
        "last_ping": datetime.utcnow().isoformat()
    },
    "TR-05-MC-6712": {
        "vehicle_number": "TR-05-MC-6712",
        "license_plate": "TR 05 MC 6712",
        "vehicle_name": "North Tripura Emergency Relief Transporter",
        "vehicle_type": "4x4 Medium Relief Carrier",
        "state": "Tripura",
        "rto_city": "Dharmanagar",
        "driver_name": "Ratan Debnath",
        "driver_phone": "+91 94365 22091",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 90.0,
        "current_fuel_litres": 63.0,
        "fuel_percentage": 70.0,
        "fuel_consumption_km_per_l": 7.0,
        "terrain_multiplier": 1.30,
        "effective_km_per_l": 5.38,
        "remaining_range_km": 338.9,
        "fuel_status": "Optimal",
        "speed_kmh": 47.0,
        "lat": 24.3800,
        "lng": 92.1800,
        "altitude_m": 68.0,
        "current_location": "Churaibari Sector",
        "current_road": "NH-08 Churaibari Interstate Checkpost",
        "destination": "Kanchanpur Relief Base",
        "cargo_manifest": "Shelter Tents & Emergency Water Filtration Pods",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-05",
        "last_ping": datetime.utcnow().isoformat()
    },
    "MN-02-HV-3108": {
        "vehicle_number": "MN-02-HV-3108",
        "license_plate": "MN 02 HV 3108",
        "vehicle_name": "Eastern Sector Supply Carrier",
        "vehicle_type": "Tactical Cargo Carrier (4x4)",
        "state": "Manipur",
        "rto_city": "Churachandpur",
        "driver_name": "Bikram Singh",
        "driver_phone": "+91 94360 44519",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 120.0,
        "current_fuel_litres": 86.0,
        "fuel_percentage": 71.7,
        "fuel_consumption_km_per_l": 5.5,
        "terrain_multiplier": 1.35,
        "effective_km_per_l": 4.07,
        "remaining_range_km": 350.0,
        "fuel_status": "Optimal",
        "speed_kmh": 48.0,
        "lat": 24.8100,
        "lng": 93.9200,
        "altitude_m": 790.0,
        "current_location": "Manipur Valley Arterial",
        "current_road": "NH-02 Imphal ➔ Kohima Highway Km 52",
        "destination": "Imphal Relief Staging Yard",
        "cargo_manifest": "Emergency Blanket Bundles & Baby Formula",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-03",
        "last_ping": datetime.utcnow().isoformat()
    },
    "MN-01-AB-5544": {
        "vehicle_number": "MN-01-AB-5544",
        "license_plate": "MN 01 AB 5544",
        "vehicle_name": "Imphal Civil Rapid Response Ambulance",
        "vehicle_type": "4WD Highland Ambulance",
        "state": "Manipur",
        "rto_city": "Imphal",
        "driver_name": "Tomba Meitei",
        "driver_phone": "+91 94361 77312",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 70.0,
        "current_fuel_litres": 58.1,
        "fuel_percentage": 83.0,
        "fuel_consumption_km_per_l": 8.5,
        "terrain_multiplier": 1.35,
        "effective_km_per_l": 6.30,
        "remaining_range_km": 366.0,
        "fuel_status": "Optimal",
        "speed_kmh": 52.0,
        "lat": 24.7800,
        "lng": 93.4200,
        "altitude_m": 920.0,
        "current_location": "Jiribam Mountain Section",
        "current_road": "NH-37 Jiribam-Imphal Mountain Lifeline",
        "destination": "RIMS Hospital Imphal",
        "cargo_manifest": "Trauma Emergency Kits & Resuscitation Equipment",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-03",
        "last_ping": datetime.utcnow().isoformat()
    },
    "NL-07-CD-3310": {
        "vehicle_number": "NL-07-CD-3310",
        "license_plate": "NL 07 CD 3310",
        "vehicle_name": "Nagaland Emergency Rescue Unit",
        "vehicle_type": "All-Terrain Rescue 4x4",
        "state": "Nagaland",
        "rto_city": "Dimapur",
        "driver_name": "Arenla Jamir",
        "driver_phone": "+91 94362 11988",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 80.0,
        "current_fuel_litres": 44.0,
        "fuel_percentage": 55.0,
        "fuel_consumption_km_per_l": 8.0,
        "terrain_multiplier": 1.40,
        "effective_km_per_l": 5.71,
        "remaining_range_km": 251.2,
        "fuel_status": "Adequate",
        "speed_kmh": 42.0,
        "lat": 25.8200,
        "lng": 93.8400,
        "altitude_m": 880.0,
        "current_location": "Kohima-Dimapur Bypass",
        "current_road": "NH-29 Kohima ➔ Dimapur Bypass Km 28",
        "destination": "Wokha Disaster Cell",
        "cargo_manifest": "Hydraulic Rescue Cutters & Emergency Satellite Kits",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-04",
        "last_ping": datetime.utcnow().isoformat()
    },
    "NL-01-TR-8819": {
        "vehicle_number": "NL-01-TR-8819",
        "license_plate": "NL 01 TR 8819",
        "vehicle_name": "Naga Hills Mountain Logistics Truck",
        "vehicle_type": "Heavy Relief Truck (6x6)",
        "state": "Nagaland",
        "rto_city": "Kohima",
        "driver_name": "Kevichusa Angami",
        "driver_phone": "+91 94360 11290",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 150.0,
        "current_fuel_litres": 100.5,
        "fuel_percentage": 67.0,
        "fuel_consumption_km_per_l": 4.2,
        "terrain_multiplier": 1.45,
        "effective_km_per_l": 2.90,
        "remaining_range_km": 291.5,
        "fuel_status": "Adequate",
        "speed_kmh": 36.0,
        "lat": 25.6100,
        "lng": 94.1300,
        "altitude_m": 1640.0,
        "current_location": "Mao Gate Boundary",
        "current_road": "NH-02 Mao Gate Border Pass",
        "destination": "Mokokchung Relief Staging Base",
        "cargo_manifest": "Prefabricated Bridge Spanners & Bailey Units",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-04",
        "last_ping": datetime.utcnow().isoformat()
    },
    "MZ-01-GH-6622": {
        "vehicle_number": "MZ-01-GH-6622",
        "license_plate": "MZ 01 GH 6622",
        "vehicle_name": "Mizoram Mountain Logistics Van",
        "vehicle_type": "High Clearance 4WD Van",
        "state": "Mizoram",
        "rto_city": "Aizawl",
        "driver_name": "Lalrintluanga",
        "driver_phone": "+91 94361 55902",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 75.0,
        "current_fuel_litres": 48.0,
        "fuel_percentage": 64.0,
        "fuel_consumption_km_per_l": 8.0,
        "terrain_multiplier": 1.40,
        "effective_km_per_l": 5.71,
        "remaining_range_km": 274.1,
        "fuel_status": "Adequate",
        "speed_kmh": 37.0,
        "lat": 23.7120,
        "lng": 92.7450,
        "altitude_m": 1130.0,
        "current_location": "Aizawl Mountain Ring",
        "current_road": "NH-54 Aizawl Outer Ring Km 18",
        "destination": "Lunglei District Hospital",
        "cargo_manifest": "Dialysis Fluids & Antivenom Doses",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-03",
        "last_ping": datetime.utcnow().isoformat()
    },
    "MZ-02-ER-3401": {
        "vehicle_number": "MZ-02-ER-3401",
        "license_plate": "MZ 02 ER 3401",
        "vehicle_name": "South Mizoram Medical Courier 4x4",
        "vehicle_type": "Mountain Rapid Response SUV",
        "state": "Mizoram",
        "rto_city": "Lunglei",
        "driver_name": "Vanlalthlana",
        "driver_phone": "+91 94363 88102",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 65.0,
        "current_fuel_litres": 50.7,
        "fuel_percentage": 78.0,
        "fuel_consumption_km_per_l": 9.0,
        "terrain_multiplier": 1.40,
        "effective_km_per_l": 6.43,
        "remaining_range_km": 326.0,
        "fuel_status": "Optimal",
        "speed_kmh": 39.0,
        "lat": 23.3200,
        "lng": 92.8100,
        "altitude_m": 1280.0,
        "current_location": "Serchhip Ridge",
        "current_road": "NH-54 Serchhip Mountain Stretch",
        "destination": "Saiha Community Health Center",
        "cargo_manifest": "Emergency Surgical Lighting Units & Pediatric Vaccines",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-03",
        "last_ping": datetime.utcnow().isoformat()
    },
    "SK-01-RL-5504": {
        "vehicle_number": "SK-01-RL-5504",
        "license_plate": "SK 01 RL 5504",
        "vehicle_name": "Himalayan Vaccine Cruiser EV",
        "vehicle_type": "High Altitude Cold-Chain EV",
        "state": "Sikkim",
        "rto_city": "Gangtok",
        "driver_name": "Karma Bhutia",
        "driver_phone": "+91 94340 77123",
        "fuel_type": "Electric EV",
        "fuel_capacity_litres": 90.0,
        "current_fuel_litres": 72.0,
        "fuel_percentage": 80.0,
        "fuel_consumption_km_per_l": 7.8,
        "terrain_multiplier": 1.25,
        "effective_km_per_l": 6.24,
        "remaining_range_km": 449.3,
        "fuel_status": "Optimal",
        "speed_kmh": 41.0,
        "lat": 27.2800,
        "lng": 88.5400,
        "altitude_m": 1420.0,
        "current_location": "Teesta Canyon Pass",
        "current_road": "NH-10 Teesta Canyon Route",
        "destination": "Mangan Remote Clinic",
        "cargo_manifest": "Insulin & Pediatric Vaccine Batches",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-04",
        "last_ping": datetime.utcnow().isoformat()
    },
    "SK-04-TR-1299": {
        "vehicle_number": "SK-04-TR-1299",
        "license_plate": "SK 04 TR 1299",
        "vehicle_name": "Kanchenjunga Extreme Terrain Hauler",
        "vehicle_type": "Extreme Alpine 6x6 Hauler",
        "state": "Sikkim",
        "rto_city": "Mangan",
        "driver_name": "Pemba Lepcha",
        "driver_phone": "+91 94341 99044",
        "fuel_type": "Diesel",
        "fuel_capacity_litres": 170.0,
        "current_fuel_litres": 120.7,
        "fuel_percentage": 71.0,
        "fuel_consumption_km_per_l": 3.8,
        "terrain_multiplier": 1.50,
        "effective_km_per_l": 2.53,
        "remaining_range_km": 305.4,
        "fuel_status": "Adequate",
        "speed_kmh": 29.0,
        "lat": 27.6100,
        "lng": 88.6400,
        "altitude_m": 2680.0,
        "current_location": "North Sikkim High Track",
        "current_road": "Chungthang ➔ Lachen Border Track",
        "destination": "Lachen Relief Depot",
        "cargo_manifest": "Heavy Thermal Blankets & Generator Fuel Drums",
        "status": "In Transit",
        "is_in_transit": True,
        "is_online": True,
        "mesh_node_id": "MESH-NODE-04",
        "last_ping": datetime.utcnow().isoformat()
    }
}

def get_all_vehicles_list() -> List[Dict]:
    """Returns all real vehicles formatted for Vehicle and VehicleRegistryItem schemas."""
    vehicles = []
    for num, v in REAL_VEHICLE_NUMBERS_DATABASE.items():
        v_copy = dict(v)
        v_copy["id"] = num
        v_copy["name"] = v.get("vehicle_name", num)
        v_copy["assigned_driver"] = v.get("driver_name", "Assigned Pilot")
        v_copy["driver_name"] = v.get("driver_name", "Assigned Pilot")
        v_copy["current_location"] = v.get("current_road") or v.get("current_location", "In Transit")
        vehicles.append(v_copy)
    return vehicles

def search_real_vehicles(
    query: Optional[str] = None,
    in_transit_only: bool = False,
    state: Optional[str] = None
) -> List[Dict]:
    """Search vehicles by plate number, driver, road, cargo, or destination."""
    all_v = get_all_vehicles_list()
    q_norm = (query or "").strip().lower().replace("-", "").replace(" ", "")

    results = []
    for v in all_v:
        if in_transit_only:
            status = (v.get("status") or "").lower()
            if not ("transit" in status or "en route" in status or "active" in status):
                continue

        if state:
            v_state = (v.get("state") or "").lower()
            if state.lower() not in v_state:
                continue

        if not q_norm:
            results.append(v)
            continue

        v_num = v.get("vehicle_number", "").lower().replace("-", "").replace(" ", "")
        v_plate = v.get("license_plate", "").lower().replace("-", "").replace(" ", "")
        v_name = v.get("vehicle_name", "").lower()
        v_driver = v.get("driver_name", "").lower()
        v_road = v.get("current_road", "").lower()
        v_dest = v.get("destination", "").lower()
        v_cargo = v.get("cargo_manifest", "").lower()
        v_city = v.get("rto_city", "").lower()

        if (q_norm in v_num or q_norm in v_plate or q_norm in v_name or
            q_norm in v_driver or q_norm in v_road or q_norm in v_dest or
            q_norm in v_cargo or q_norm in v_city):
            results.append(v)

    return results
